# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import multiselectfield.db.fields
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('addr1', models.CharField(max_length=100, null=True, blank=True)),
                ('addr2', models.CharField(max_length=100, null=True, blank=True)),
                ('one_off_city', models.CharField(max_length=100, null=True, blank=True)),
                ('one_off_state', models.CharField(max_length=30, null=True, blank=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_address_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('denomination', models.CharField(blank=True, max_length=20, null=True, choices=[(b'christian', b'Christian'), (b'satanic', b'Satanic')])),
                ('address', models.ForeignKey(blank=True, to='pennypress.Address', null=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_church_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_church_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'churches',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(related_name='pennypress_county_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'counties',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Dateline',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, null=True, blank=True)),
                ('address', models.ForeignKey(blank=True, to='pennypress.Address', null=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_dateline_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_dateline_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True, blank=True)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField(null=True, blank=True)),
                ('one_off_address', models.TextField(null=True, blank=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('address', models.ForeignKey(related_name='events_at_this_address', blank=True, to='pennypress.Address', null=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_event_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(null=True, blank=True)),
                ('one_off_address', models.TextField(null=True, blank=True)),
                ('start_time', models.TimeField(null=True, blank=True)),
                ('duration', models.DecimalField(help_text=b'Hours', max_digits=5, decimal_places=2)),
                ('start_date', models.DateField(null=True, blank=True)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('repeat_expression', models.CharField(help_text=b'Use the days of the Week or other expressions like:\n        weekly style:\n            Monday\n            Monday, Wednesday, Friday\n        monthly style:\n            first Sunday\n            last friday\n            biweekly wednesdays\n    ', max_length=100, null=True, blank=True)),
                ('address', models.ForeignKey(related_name='eventtemplates_for_this_address', blank=True, to='pennypress.Address', null=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_eventtemplate_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('live', models.NullBooleanField(default=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_eventtype_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_eventtype_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique_for_date=b'pub_date')),
                ('subtitle', models.CharField(max_length=200, null=True, blank=True)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(related_name='pennypress_feed_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('status', models.CharField(default=b'show', max_length=10, null=True, blank=True, choices=[(b'show', b'Show'), (b'hide', b'Hide')])),
                ('created_by', models.ForeignKey(related_name='pennypress_feeditem_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('feed', models.ForeignKey(to='pennypress.Feed')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique_for_date=b'pub_date')),
                ('subtitle', models.CharField(max_length=200, null=True, blank=True)),
                ('guid', models.CharField(max_length=100, null=True, blank=True)),
                ('icon', models.ImageField(null=True, upload_to=b'streamitems/%Y/%m/%d', blank=True)),
                ('body', models.TextField(null=True, blank=True)),
                ('link', models.URLField(null=True, blank=True)),
                ('status', models.CharField(default=b'show', max_length=10, null=True, blank=True, choices=[(b'show', b'Show'), (b'hide', b'Hide')])),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(related_name='pennypress_item_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(null=True, blank=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_itemtype_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_itemtype_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100, null=True, blank=True)),
                ('alt_text', models.CharField(max_length=200, null=True, blank=True)),
                ('target', models.CharField(blank=True, max_length=50, null=True, choices=[(b'_blank', b'New Window'), (b'', b'Same Window')])),
                ('created_by', models.ForeignKey(related_name='pennypress_link_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_link_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('live', models.NullBooleanField(default=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_nav_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('parent', models.ForeignKey(blank=True, to='pennypress.Nav', null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_nav_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.ForeignKey(blank=True, to='pennypress.Address', null=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_organization_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_organization_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.ForeignKey(blank=True, to='pennypress.Address', null=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_park_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique_for_date=b'pub_date')),
                ('subtitle', models.CharField(max_length=200, null=True, blank=True)),
                ('image', models.ImageField(upload_to=b'')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(related_name='pennypress_photo_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('created_by', models.ForeignKey(related_name='pennypress_place_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('latitude', models.DecimalField(null=True, max_digits=7, decimal_places=4, blank=True)),
                ('longitude', models.DecimalField(null=True, max_digits=7, decimal_places=4, blank=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_point_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_point_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('hours', models.TextField()),
                ('description', models.TextField()),
                ('address', models.ForeignKey(blank=True, to='pennypress.Address', null=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_pollingstation_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_pollingstation_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('grades', multiselectfield.db.fields.MultiSelectField(max_length=55, choices=[(-1, b'Pre-K'), (0, b'Kindergarten'), (1, b'First Grade'), (2, b'Second Grade'), (3, b'Third Grade'), (4, b'Fourth Grade'), (5, b'Fifth Grade'), (6, b'Sixth Grade'), (7, b'Seventh Grade'), (8, b'Eight Grade'), (9, b'HS Freshman'), (10, b'HS Sophomore'), (11, b'HS Junior'), (12, b'HS Senior Grade'), (13, b'Freshman'), (14, b'Sophomore'), (15, b'Junior'), (16, b'Senior'), (17, b'Associates'), (18, b'Bachellors'), (19, b'Masters'), (20, b'Doctorate')])),
                ('address', models.ForeignKey(blank=True, to='pennypress.Address', null=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_school_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('external_rss_source', models.URLField(help_text=b'Links come from this source.', null=True, blank=True)),
                ('external_page', models.URLField(help_text=b'Links to this section will redirect to this url.', null=True, blank=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_section_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('created_by', models.ForeignKey(related_name='pennypress_sport_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_sport_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('abbr', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(related_name='pennypress_state_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('point', models.ForeignKey(blank=True, to='pennypress.Point', null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_state_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique_for_date=b'pub_date')),
                ('subtitle', models.CharField(max_length=200, null=True, blank=True)),
                ('tease', models.TextField(max_length=200, null=True, blank=True)),
                ('one_off_dateline', models.CharField(max_length=100, null=True, blank=True)),
                ('body', models.TextField(max_length=10000, null=True, blank=True)),
                ('footer', models.TextField(max_length=200, null=True, blank=True)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(related_name='pennypress_story_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('dateline', models.ForeignKey(blank=True, to='pennypress.Dateline', null=True)),
                ('lead_photo', models.ForeignKey(blank=True, to='pennypress.Photo', null=True)),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('status', models.CharField(max_length=10, choices=[(b'live', b'Live'), (b'suspended', b'Suspended')])),
                ('config', models.TextField(null=True, blank=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('pub_policy', models.CharField(default=b'auto', max_length=10, choices=[(b'manual', b'Manual'), (b'auto', b'Automatic')])),
                ('update_policy', models.CharField(default=b'extend', max_length=10, choices=[(b'extend', b'Extend'), (b'replace', b'Replace')])),
                ('created_by', models.ForeignKey(related_name='pennypress_stream_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='StreamType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(null=True, blank=True)),
                ('created_by', models.ForeignKey(related_name='pennypress_streamtype_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_streamtype_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('created_by', models.ForeignKey(related_name='pennypress_tag_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('parent', models.ForeignKey(blank=True, to='pennypress.Tag', null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_tag_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique_for_date=b'pub_date')),
                ('subtitle', models.CharField(max_length=200, null=True, blank=True)),
                ('video', models.URLField()),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(related_name='pennypress_video_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('photo', models.ForeignKey(blank=True, to='pennypress.Photo', null=True)),
                ('tags', models.ManyToManyField(to='pennypress.Tag', null=True, blank=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_video_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('city', models.ForeignKey(to='pennypress.City')),
                ('created_by', models.ForeignKey(related_name='pennypress_zipcode_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('point', models.ForeignKey(blank=True, to='pennypress.Point', null=True)),
                ('updated_by', models.ForeignKey(related_name='pennypress_zipcode_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_type',
            field=models.ForeignKey(to='pennypress.StreamType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='stream',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_stream_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(to='pennypress.Tag', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='story',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_story_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='section',
            name='excluded_tags',
            field=models.ManyToManyField(related_name='excluded_from', to='pennypress.Tag'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='section',
            name='included_tags',
            field=models.ManyToManyField(related_name='included_in', to='pennypress.Tag'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='section',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_section_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='school',
            name='sports',
            field=models.ManyToManyField(to='pennypress.Sport', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='school',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_school_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set([('latitude', 'longitude')]),
        ),
        migrations.AddField(
            model_name='place',
            name='point',
            field=models.ForeignKey(to='pennypress.Point'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='place',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_place_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='pennypress.Tag', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photo',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_photo_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='park',
            name='sports',
            field=models.ManyToManyField(to='pennypress.Sport', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='park',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_park_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(to='pennypress.ItemType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='item',
            name='stream',
            field=models.ForeignKey(to='pennypress.Stream'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='pennypress.Tag', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_item_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='feeditem',
            name='item',
            field=models.ForeignKey(to='pennypress.Item'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='feeditem',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_feeditem_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='feed',
            name='streams',
            field=models.ManyToManyField(to='pennypress.Stream', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='feed',
            name='tags',
            field=models.ManyToManyField(to='pennypress.Tag', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='feed',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_feed_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='eventtypes',
            field=models.ManyToManyField(to='pennypress.EventType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='organization',
            field=models.ForeignKey(related_name='eventtemplates', blank=True, to='pennypress.Organization', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_eventtemplate_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='eventtemplate',
            field=models.ForeignKey(blank=True, to='pennypress.EventTemplate', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='eventtypes',
            field=models.ManyToManyField(to='pennypress.EventType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(related_name='events', blank=True, to='pennypress.Organization', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_event_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='county',
            name='point',
            field=models.ForeignKey(blank=True, to='pennypress.Point', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='county',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_county_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(to='pennypress.County'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='city',
            name='created_by',
            field=models.ForeignKey(related_name='pennypress_city_creator', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='city',
            name='point',
            field=models.ForeignKey(blank=True, to='pennypress.Point', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(to='pennypress.State'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='city',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_city_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='address',
            name='point',
            field=models.ForeignKey(blank=True, to='pennypress.Point', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='address',
            name='updated_by',
            field=models.ForeignKey(related_name='pennypress_address_updater', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.ForeignKey(to='pennypress.ZipCode'),
            preserve_default=True,
        ),
    ]
